### ISSUE TITLE
Hi Dive Subtitles

### ISSUE THREAD

**Issue by scj643** [scj643/plugin.video.vrv#4]
As it is currently Hi Dive subtitles are not being formatted properly.

**Comment by scj643** [comment]
The issue seems to be with subtitles in the `vtt` format.

**Comment by scj643** [comment]
This issue possibly has to do with ffmpeg not handling the styling of the subtitles. A workaround could be to convert the subtitles.

**Comment by brandontolbird** [comment]
That's weird, because I'm not having that issue on my end.

EDIT: Oh, you said formatting, not displaying. Nevermind.

**Comment by brandontolbird** [comment]
Think I found a workaround in the vein you mentioned: convert the vtt subtitles to ass format. Seems trivial enough. Working on a prototype now, but since I'm on vacation, this might take a bit.

**Comment by brandontolbird** [comment]
I've implemented the code in the vtt-conv branch in my forked repo (I tried pushing to yours, but was getting a 403 error). The code is in a rough state(the templates/settings need tweaking), but it does try to follow the positioning directives in the vtt file. See attached.
![screenshot002](https://user-images.githubusercontent.com/41023732/53469302-f7ab2b80-3a22-11e9-8640-12f215575bef.png)

**Comment by scj643** [comment]
Just create a merge request when it's ready

**Comment by brandontolbird** [comment]
Ok, will do.

**Comment by scj643** [comment]
#6 fixes this
